exports.WEB_FILEPATH = __dirname + "/";

exports.MAIN_MENU_WIDTH = 800;
exports.MAIN_MENU_HEIGHT = 600;

exports.LOCALHOST_ADDRESS = "localhost";
exports.HTTP_PREFIX = "http://";
exports.DEFAULT_PORT = 4690;
exports.GOOGLE_MAPS_API_URL = "https://maps.googleapis.com/maps/api/js?key=";
exports.GOOGLE_MAPS_API_LIBS = "&libraries=places"; // Extra libraries tagged onto the url+key

exports.IPC_EVENTS = {
    // RTM: renderer to main
    // MTR: main to renderer
    HERES_ACTIVE_PLAYER_INFO_RTM: "HERES_ACTIVE_PLAYER_INFO_RTM",
    GAME_START_LOAD_RTM: "GAME_START_LOAD_RTM",
    GAME_START_LOAD_MTR: "GAME_START_LOAD_MTR"
};

exports.IO_EVENTS = {
    // STC: server to client
    // CTS: client to server
    HERES_GAME_DATA_STC: "HERES_GAME_DATA_STC",
    HERES_CONNECTED_PLAYER_INFOS_STC: "HERES_CONNECTED_PLAYER_INFOS_STC",
    HERES_MY_PLAYER_INFO_CTS: "HERES_MY_PLAYER_INFO_CTS",
    NEW_CONNECTED_PLAYER_INFO_STC: "NEW_CONNECTED_PLAYER_INFO_STC",
    NEW_DISCONNECTED_PLAYER_STC: "NEW_DISCONNECTED_PLAYER_INFO_STC",
    SEND_CHAT_CTS: "SEND_CHAT_CTS",
    INCOMING_CHAT_STC: "INCOMING_CHAT_STC"
};

exports.GLOBAL_NAMES = {
    ACTIVE_PLAYER_INFO: "MAPOCALYPSE_ACTIVE_PLAYER_INFO",
    SERVER: "MAPOCALYPSE_SERVER",
    GAME_LOAD_INFO: "MAPOCALYPSE_GAME_LOAD_INFO",
    CLEAR_GAME_LOAD_INFO: "MAPOCALYPSE_CLEAR_GAME_LOAD_INFO"
};